# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'dotnetcore:$(version)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output out
  displayName: 'Build & Test & Publish'
  
- task: PublishTestResults@2
  displayName: 'Collect Test Result'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
    
- script: |      
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)
  displayName: 'Push to Docker'

- script: sed -i 's/:builtVersion/:$(version)/g'  pipeline/azure-deployment.kubernetes.yml
  displayName: 'Change version number in deployment file'

- task: PublishBuildArtifacts@1
  displayName: 'Publish deployment file'
  inputs:
    PathtoPublish: 'pipeline/azure-deployment.kubernetes.yml'
    ArtifactName: K8SYml
