apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Chart.Name}}-deployment'
  labels:
    component: backend
    app: {{.Chart.Name}}
    helm.sh/chart: '{{.Chart.Name}}-{{.Chart.Version}}'  
    instance: {{.Values.buildNumber | quote}} 
    release/name: {{.Release.Name}}  
    release/revision: {{.Release.Revision | quote}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:	 
      containers:
        - name: redisdb
          image: redis
          ports:
            - containerPort: 6379
        - name: {{.Chart.Name}}
          image: zzplezz/{{.Chart.Name}}:{{.Chart.Version}}-{{.Values.buildId}}
          ports:
            - containerPort: 80
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: {{ .Values.applicationInsights.InstrumentationKey }}