apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Chart.Name}}-deployment'
  labels:
    component: backend
    name: {{.Chart.Name}}
    helm.sh/chart: '{{.Chart.Name}}-{{.Chart.Version}}'  
    instance: {{.Values.buildNumber | quote}} 
    release/name: {{.Release.Name}}  
    release/revision: {{.Release.Revision}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{.Chart.Name}}
  template:
    metadata:
      labels:
        name: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: zzplezz/{{.Chart.Name}}:{{.Chart.Version}}-{{.Values.buildId}}
        ports:
        - containerPort: 80