apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Chart.Name}}-deployment'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: {{.Chart.Name}}   
    app.kubernetes.io/instance: '{{.Values.buildNumber}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: zzplezz/{{.Chart.Name}}:{{.Chart.Version}}-{{.Values.buildId}}
        ports:
        - containerPort: 80