apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Chart.Name}}-{{.Release.Name}}_deployment'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: {{.Chart.Name}}   
    app.kubernetes.io/instance: {{.Release.Name}}    
    helm.sh/chart: '{{.Chart.Name}}-{{.Chart.Version}}'    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: zzplezz/{{.Chart.Name}}:{{.Values.buildTag}}
        ports:
        - containerPort: 80