apiVersion: v1
kind: Service
metadata:
  name: '{{.Chart.Name}}-{{.Values.buildTag}}-service'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: {{.Chart.Name}}   
    app.kubernetes.io/instance: {{.Release.Name}}   
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: {{.Chart.Name}}