apiVersion: v1
kind: Service
metadata:
  name: '{{.Chart.Name}}-service'
  labels:
    component: backend
    helm.sh/chart: '{{.Chart.Name}}-{{.Chart.Version}}'  
    instance: {{.Values.buildNumber | quote}} 
    release/name: {{.Release.Name}}  
    release/revision: {{.Release.Revision | quote}}  
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: {{.Chart.Name}}