apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  labels:
    app: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: zzplezz/dotnetcore:{{.Values.buildNumber}}
        ports:
        - containerPort: 80