apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetcoresample
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dotnetcoresample
    spec:
      containers:
      - name: dotnetcoresample
        image: adventworks/dotnetcoresample
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcoresample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnetcoresample
